triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: input_image
states:
    input_image_state:
        component: meya.input_image
        properties:
            text: Please take a picture or upload an image and we will search for a matching color
            output: color_url
            scope: flow
        error_message: Sorry, but we did not detect an image file
    find_image_color:
        component: closest_color
    find_color:
        component: meya.text_buttons
        properties:
            text: Is this the color you were looking for?
            mode: quick_reply
            buttons:
                - text: 'Yes'
                  flow: last_question
                - text: 'No'
                  flow: color_tone
